"""Add Book out and in

Revision ID: 00861e08c1ea
Revises: bec2c4dd1d13
Create Date: 2024-03-27 21:16:06.011580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00861e08c1ea'
down_revision = 'bec2c4dd1d13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('booked_out_by', sa.String(length=128), nullable=True),
    sa.Column('booked_out_to', sa.String(length=128), nullable=True),
    sa.Column('booked_out_quantity', sa.Integer(), nullable=True),
    sa.Column('booked_out_timestamp', sa.DateTime(), nullable=True),
    sa.Column('booked_in_timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('booked_out', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_column('booked_out')

    op.drop_table('usage')
    # ### end Alembic commands ###
