"""added categories

Revision ID: 096e813327d6
Revises: 133fe30f8052
Create Date: 2024-03-27 14:30:11.392459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '096e813327d6'
down_revision = '133fe30f8052'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('category')
    # ### end Alembic commands ###
