"""Add supplier part no and invoice no

Revision ID: 4e77cec75d43
Revises: 096e813327d6
Create Date: 2024-03-27 15:38:22.076651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e77cec75d43'
down_revision = '096e813327d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supplier_part_no', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('invoice_no', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_column('invoice_no')
        batch_op.drop_column('supplier_part_no')

    # ### end Alembic commands ###
