"""removed image path to transactions

Revision ID: 6509e7dac0cc
Revises: e026a7f76d45
Create Date: 2024-04-02 11:28:25.697625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6509e7dac0cc'
down_revision = 'e026a7f76d45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_column('image_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.VARCHAR(length=256), nullable=True))

    # ### end Alembic commands ###
