"""Add doc_no to transactions

Revision ID: 9179d3830309
Revises: 00861e08c1ea
Create Date: 2024-04-02 08:55:24.485279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9179d3830309'
down_revision = '00861e08c1ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('doc_no', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('doc_no')

    # ### end Alembic commands ###
