"""added bin assignments

Revision ID: e5ce193fc724
Revises: 91ae327a01f4
Create Date: 2024-04-02 13:03:48.272438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5ce193fc724'
down_revision = '91ae327a01f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bin_assignment', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('bulk_bin_assignment', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_column('bulk_bin_assignment')
        batch_op.drop_column('bin_assignment')

    # ### end Alembic commands ###
